[package]
name = "arroyo-storage"
version = "0.5.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []

[dependencies]
arroyo-types = { path = "../arroyo-types" }
bytes = "1.4.0"

object_store = {version = "0.6.1", features = ["aws", "gcp"]}
regex = "1.9.5"
thiserror = "1"
