[package]
name = "arroyo"
version = "0.15.0-dev"
edition = "2021"

[features]
default = ["all-connectors"]
profiling = ["tikv-jemallocator/profiling"]
python = ["arroyo-udf-python/python-enabled"]
all-connectors = ["arroyo-connectors/all-connectors"]
redis = ["arroyo-connectors/redis"]
fluvio = ["arroyo-connectors/fluvio"]
kinesis = ["arroyo-connectors/kinesis"]
rabbitmq = ["arroyo-connectors/rabbitmq"]
mqtt = ["arroyo-connectors/mqtt"]
nats = ["arroyo-connectors/nats"]

[dependencies]
arroyo-types = { path ="../arroyo-types" }
arroyo-controller = { path = "../arroyo-controller" }
arroyo-api = { path = "../arroyo-api" }
arroyo-worker = { path = "../arroyo-worker" }
arroyo-server-common = { path = "../arroyo-server-common" }
arroyo-compiler-service = { path = "../arroyo-compiler-service" }
arroyo-node = { path = "../arroyo-node" }
arroyo-rpc = { path = "../arroyo-rpc" }
arroyo-openapi = { path ="../arroyo-openapi" }
arroyo-storage = { path = "../arroyo-storage" }
arroyo-udf-python = { path = "../arroyo-udf/arroyo-udf-python" }
arroyo-planner = { path = "../arroyo-planner" }
arroyo-connectors = { path = "../arroyo-connectors", default-features = false }

clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde = "1"
serde_json = "1"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = [ "env-filter", "json" ]}

tokio-postgres = { version = "*", features = ["with-serde_json-1", "with-time-0_3", "with-uuid-1"] }
deadpool-postgres = { workspace = true }
cornucopia_async = { workspace = true }
rusqlite = {  workspace = true, features = ["backup"] }
uuid = { version = "1.7.0", features = ["v4"] }
refinery = { version = "0.8.14" , features = ["tokio-postgres", "rusqlite"] }
anyhow = { version = "1.0.79"}
rand = { workspace = true }
reqwest = { workspace = true}
clio = { version = "0.3.5", features = ["clap", "clap-parse"] }
async-trait = "0.1.80"
open = '5.3.0'


[target.'cfg(all(not(target_env = "msvc"), any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
tikv-jemallocator = { version = "0.6.0", features = ["unprefixed_malloc_on_supported_platforms"]}