[package]
name = "arroyo-sql"
version = "0.1.0"
edition = "2021"


[dependencies]
datafusion = "20.0"
datafusion-expr = "20.0"
datafusion-common = "20.0"
arroyo-datastream = { path = "../arroyo-datastream" }
arroyo-types = { path = "../arroyo-types" }
arrow-schema = {version = "34.0", features = ["serde"]}
serde = {version = "1", features = ["derive"]}
bincode = { version = "2.0.0-rc.3", features = ["serde"]}
petgraph = "0.6"
tokio = "1.27"
quote = "1.0"
regex = "1"
arrow = { version = "34.0.0", default-features = false }
anyhow = {version = "1.0.70", features = ["backtrace"]}

proc-macro2 = "1"
syn = {version = "1", features = ["full", "parsing"]}