
[workspace]
members = [
  "pipeline",
  "types",
]

exclude = [
  "wasm-fns",
]
[workspace.dependencies]
arrow = { version = "46.0.0" }
arrow-buffer = { version = "46.0.0" }
arrow-array = { version = "46.0.0" }
arrow-schema = { version = "46.0.0" }
parquet = { version = "46.0.0" }


[patch.crates-io]
parquet = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '46.0.0/parquet_bytes'}
arrow = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '46.0.0/parquet_bytes'}
arrow-buffer = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '46.0.0/parquet_bytes'}
arrow-array = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '46.0.0/parquet_bytes'}
arrow-schema = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '46.0.0/parquet_bytes'}
object_store = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = 'object_store/put_part_api'}
