
[workspace]
members = [
  "pipeline",
  "types",
  "udfs",
]

exclude = [
  "wasm-fns",
]
[workspace.dependencies]
arrow = { version = "43.0.0" }
arrow-buffer = { version = "43.0.0" }
arrow-array = { version = "43.0.0" }
arrow-schema = { version = "43.0.0" }
parquet = { version = "43.0.0" }

[patch.crates-io]
parquet = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '43.0.0/arroyo_patches-1'}
arrow = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '43.0.0/arroyo_patches-1'}
arrow-buffer = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '43.0.0/arroyo_patches-1'}
arrow-array = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '43.0.0/arroyo_patches-1'}
arrow-schema = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '43.0.0/arroyo_patches-1'}
object_store = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '43.0.0/arroyo_patches-1'}
