[package]
name = "copy-artifacts"
version = "0.6.0"
edition = "2021"

[dependencies]
arroyo-storage = { path = "../arroyo-storage" }
regex = "1"
tokio = {version = "1", features = ["fs", "rt", "net"]}
