[package]
name = "arroyo-openapi"
version = "0.4.1"
edition = "2021"

[dependencies]
arroyo-api = { path = "../arroyo-api" }

[build-dependencies]
arroyo-api = { path = "../arroyo-api" }
utoipa = "3"
