global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    static_configs:
      - targets: ['localhost:9091']

  - job_name: arroyo-controller
    static_configs:
      - targets: ['localhost:9191']

  - job_name: arroyo-api
    static_configs:
      - targets: ['localhost:8001']
