apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arroyo.fullname" . }}-api
  labels:
    {{- include "arroyo.labels" . | nindent 4 }}
    app: {{ include "arroyo.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "arroyo.fullname" . }}-api
  template:
    metadata:
      labels:
        {{- include "arroyo.labels" . | nindent 8 }}
        app: {{ include "arroyo.fullname" . }}-api
      annotations:
        {{- if .Values.prometheus.setAnnotations }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8002"
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arroyo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: arroyo-api
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        args: ["api"]
        env:
        {{- include "arroyo.databaseEnvVars" . | nindent 8 }}
        - name: CONTROLLER_ADDR
          value: "http://{{ include "arroyo.fullname" . }}-controller:9190"
        - name: PROM_ENDPOINT
          value: "{{ include "arroyo.prometheusEndpoint" .}}"
        - name: API_METRICS_RATE
          value: "{{ .Values.prometheus.queryRate }}"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: admin
        livenessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 5
        {{- if .Values.api.resources }}
        resources: {{- toYaml .Values.api.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arroyo.fullname" . }}-api
spec:
  selector:
    app: {{ include "arroyo.fullname" . }}-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.apiPort }}
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.grpcPort }}
      targetPort: 8001
