apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arroyo.fullname" . }}-controller
  labels:
    {{- include "arroyo.labels" . | nindent 4 }}
    app: {{ include "arroyo.fullname" . }}-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "arroyo.fullname" . }}-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      {{- include "arroyo.labels" . | nindent 8 }}
        app: {{ include "arroyo.fullname" . }}-controller
      annotations:
        {{- if .Values.prometheus.setAnnotations }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8001"
        {{- end }}
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "arroyo.serviceAccountName" . }}
      volumes:
      {{- if .Values.volumes }}
      {{- include "tplvalues.render" (dict "value" .Values.volumes "context" $) | nindent 10 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 10 }}
      {{- end }}
      initContainers:
      - name: migrate-database
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        command: [ "/app/arroyo-bin", "migrate", "--wait", "300" ]
        env:
        {{- include "arroyo.databaseEnvVars" . | nindent 8 }}
      containers:
      - name: arroyo-controller
        securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        command: ["/app/arroyo-bin", "cluster"]

        env:
        {{- include "arroyo.storageEnvVars" . | nindent 8 }}
        - name: CHECKPOINT_URL
          value: {{ required "A valid .Values.checkpointUrl entry required!" .Values.checkpointUrl }}
        - name: ARTIFACT_URL
          value: {{ required "A valid .Values.artifactUrl entry required!" .Values.artifactUrl }}

        {{- include "arroyo.databaseEnvVars" . | nindent 8 }}
        - name: CONTROLLER_ADDR
          value: "http://{{ include "arroyo.fullname" . }}:{{ .Values.controller.service.grpcPort }}"
        - name: GRPC_PORT
          value: {{ .Values.controller.service.grpcPort | quote }}
        - name: ADMIN_PORT
          value: {{ .Values.controller.service.adminPort | quote }}
        - name: HTTP_PORT
          value: {{ .Values.controller.service.httpPort | quote }}
        - name: COMPILER_GRPC_PORT
          value: {{ .Values.controller.service.compilerPort | quote }}
        - name: PROM_ENDPOINT
          value: "{{ include "arroyo.prometheusEndpoint" .}}"
        - name: API_METRICS_RATE
          value: "{{ .Values.prometheus.queryRate }}"
        - name: SCHEDULER
          value: "kubernetes"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_WORKER_NAME
          value: "{{ include "arroyo.fullname" . }}"
        - name: K8S_WORKER_LABELS
          value: {{ include "arroyo.labels" . | quote }}
        - name: K8S_WORKER_ANNOTATIONS
        {{- if .Values.prometheus.setAnnotations }}
          {{- $merged := merge (dict "prometheus.io/scrape" "true" "prometheus.io/path" "/metrics" "prometheus.io/port" "6901") .Values.podAnnotations  }}
          value: {{ toYaml $merged | quote }}
        {{- else }}
          value: {{ .Values.podAnnotations | toYaml | quote }}
        {{- end }}
        - name: K8S_WORKER_IMAGE
          value: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        - name: K8S_WORKER_IMAGE_PULL_POLICY
          value: "{{ .Values.worker.image.pullPolicy }}"
        # TODO: image pull secret
        {{- if .Values.serviceAccount.name }}
        - name: K8S_WORKER_SERVICE_ACCOUNT_NAME
          value: "{{ template "arroyo.serviceAccountName" . }}"
        {{- end }}
        - name: K8S_WORKER_RESOURCES
          value: {{ .Values.worker.resources | toYaml | quote }}
        - name: K8S_WORKER_SLOTS
          value: {{ .Values.worker.slots | quote }}
        {{- if .Values.volumes }}
        - name: K8S_WORKER_VOLUMES
          value: {{ .Values.volumes | toYaml | quote }}
        {{- end }}
        {{- if .Values.volumeMounts }}
        - name: K8S_WORKER_VOLUME_MOUNTS
          value: {{ .Values.volumeMounts | toYaml | quote }}
        {{- end }}
        {{- if .Values.existingConfigMap }}
        - name: K8S_WORKER_CONFIG_MAP
          value: {{ .Values.existingConfigMap }}
        {{- end }}

        {{- include "arroyo.existingConfigMap" . | nindent 8 }}

        ports:
        - containerPort: {{ .Values.controller.service.grpcPort }}
          name: grpc
        - containerPort: {{ .Values.controller.service.adminPort }}
          name: admin
        - containerPort: {{ .Values.controller.service.httpPort }}
          name: http
        livenessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 5
        volumeMounts:
        {{- if .Values.volumeMounts }}
        {{- include "tplvalues.render" (dict "value" .Values.volumeMounts "context" $) | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arroyo.fullname" . }}
spec:
  selector:
    app: {{ include "arroyo.fullname" . }}-controller
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.controller.service.grpcPort }}
      targetPort: 9190
    - name: admin
      protocol: TCP
      port: {{ .Values.controller.service.adminPort }}
      targetPort: 9191
    - name: http
      protocol: TCP
      port: {{ .Values.controller.service.httpPort }}
      targetPort: 80
