apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes: {{ .Values.persistence.accessModes }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: {{ .Values.persistence.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: {{ .Values.persistence.nodeAffinity.hostname }}
