[package]
name = "arroyo-udf"
version = "0.10.0-dev"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
futures = "0.3"
arrow = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '50.0.0/parquet_bytes', features = ["ffi"]}
async-ffi = { version = "0.5.0", features = ["macros"] }