checkpoint-url = "/tmp/arroyo/checkpoints"
default-checkpoint-interval = "10s"

[pipeline]
source-batch-size = 512
source-batch-linger = "100ms"
update-aggregate-flush-interval = "1s"
allowed-restarts = 20
worker-heartbeat-timeout = "30s"
healthy-duration = "2m"
worker-startup-time = "10m"
task-startup-time = "2m"

[pipeline.compaction]
enabled = false
checkpoints-to-compact = 4

# Services

[api]
bind-address = "0.0.0.0"
http-port = 5115

[controller]
bind-address = "0.0.0.0"
rpc-port = 5116
scheduler = "process"

[compiler]
bind-address = "0.0.0.0"
rpc-port = 5117
install-clang = true
install-rustc = true
artifact-url = "/tmp/arroyo/artifacts"
build-dir = "/tmp/arroyo/build-dir"

[worker]
bind-address = "0.0.0.0"
rpc-port = 0
data-port = 0
task-slots = 16
queue-size = 8192

[node]
bind-address = "0.0.0.0"
rpc-port = 5118
task-slots = 16

[admin]
bind-address = "0.0.0.0"
http-port = 5114


# Schedulers

[process-scheduler]
slots-per-process = 16

[kubernetes-scheduler]
namespace = "default"
resource-mode = "per-slot"

[kubernetes-scheduler.worker]
name-prefix = "arroyo"
image = "ghcr.io/arroyosystems/arroyo:latest"
image-pull-policy = "IfNotPresent"
service-account-name = "default"
resources = { requests = { cpu = "900m",  memory = "500Mi" } }
task-slots = 16
command = "/app/arroyo worker"

# other

[database]
type = "sqlite"

[database.postgres]
database-name = "arroyo"
host = "localhost"
port = 5432
user = "arroyo"
password = "arroyo"

[logging]
format = "plaintext" # option: plaintext / json / logfmt 
nonblocking = false
enable-file-line = false
enable-file-name = false 
buffered-lines-limit = 4096
