[package]
name = "arroyo-sql-macro"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1"
arroyo-sql = { path = "../arroyo-sql" }
arroyo-controller = { path = "../arroyo-controller" }
arroyo-datastream = { path = "../arroyo-datastream" }
