[package]
name = "arroyo-udf-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
arroyo-udf-common = { path = "../arroyo-udf-common" }

tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
futures = "0.3"
arrow = {git = 'https://github.com/ArroyoSystems/arrow-rs', branch = '50.0.0/parquet_bytes', features = ["ffi"]}
async-ffi = { version = "0.5.0", features = ["macros"] }
