[package]
name = "arroyo-udf-plugin"
version = "0.1.1"
edition = "2021"
authors = ["Arroyo Systems <support@arroyo.systems>"]
license = "MIT OR Apache-2.0"
readme = "../../../README.md"
repository = "https://github.com/ArroyoSystems/arroyo"
homepage = "https://arroyo.dev"
categories = ["database-implementations", "web-programming"]
keywords = ["streaming", "data", "sql", "event-processing"]

description = "Plugin interface for Arroyo UDFs"

[dependencies]
arroyo-udf-common = { path = "../arroyo-udf-common" }
arroyo-udf-macros = { path = "../arroyo-udf-macros" }

tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
futures = "0.3"
arrow = { workspace = true, features = ["ffi"]}
async-ffi = { version = "0.5.0", features = ["macros"] }
