nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local

image:
  repository: ghcr.io/arroyosystems/arroyo
  tag: "tip"
imagePullPolicy: IfNotPresent
imagePullSecrets: []

controller:
  replicas: 1

  service:
    type: ClusterIP
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    grpcPort: 5116
    compilerPort: 5117
    adminPort: 5114
    httpPort: 80

  resources:
    limits: {}
    requests:
      memory: 256Mi
      cpu: 500m

  probeInitialDelaySeconds: 5

  podLabels: {}

  initContainers:
    migrate:
      resources: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  resources:
    limits: {}
    requests:
      memory: 490Mi
      cpu: 900m
  slots: 16
  nodeSelector: {}
  tolerations: []

postgresql:
  deploy: true

  externalDatabase:
    host: localhost
    port: 5432
    name: arroyo
    user: arroyo
    password: arroyo
    existingSecret: ""
    existingSecretPasswordKey: "password"

  auth:
    username: arroyo
    password: arroyo
    database: arroyo

  primary:
    initdb:
      user: postgres

  serviceAccount:
    create: true
    name: arroyo-postgresql

  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 15.3.0-debian-11-r24

prometheus:
  setAnnotations: true

s3:
  region: ""

artifactUrl: ""
checkpointUrl: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

role:
  create: true

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

volumes: []
volumeMounts: []

existingConfigMap: ""

env: []

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts: []
  tls: []

gateway:
  httpRoute:
    enabled: false
    annotations: {}
    parentRefs: []
    hostnames: []
    matches: []

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""
