[package]
name = "arroyo-types"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.3"
base64 = "0.21"
md-5 = "0.10"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
