env:
  browser: true
  es2021: true
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - unused-imports
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars: off
  unused-imports/no-unused-imports: error
  no-trailing-spaces: error
