[package]
name = "arroyo-worker"
version = "0.11.0-dev"
edition = "2021"

[features]
default = []
kafka-sal = ["arroyo-connectors/kafka-sasl"]

[dependencies]
arroyo-types = { path = "../arroyo-types" }
arroyo-state = { path = "../arroyo-state" }
arroyo-rpc = { path = "../arroyo-rpc" }
arroyo-server-common = { path = "../arroyo-server-common" }
arroyo-storage = { path = "../arroyo-storage" }
arroyo-metrics =  { path = "../arroyo-metrics" }
arroyo-formats = { path = "../arroyo-formats" }
arroyo-datastream = { path = "../arroyo-datastream" }
arroyo-df = { path = "../arroyo-df" }
arroyo-operator = { path = "../arroyo-operator" }
arroyo-connectors = { path = "../arroyo-connectors" }
arroyo-udf-host = { path = "../arroyo-udf/arroyo-udf-host" }

ahash = { workspace = true }
rand = "0.8"
bincode = "2.0.0-rc.3"
lazy_static = "1.4.0"
petgraph = "0.6"
chrono = "0.4"
prometheus = {version = "0.13", features = ["process"] }
futures = "0.3"
tokio = { version = "1", features = ["full", "tracing"] }
tokio-stream = { version = "0.1", features = ["full"] }
async-compression = { version = "0.4.3", features = ["tokio", "gzip"] }
async-trait = "0.1.68"
async-stream = "0.3.4"
stacker = "0.1"
bytes = "1.4"
once_cell = "1.17.1"
local-ip-address = "0.5"
serde_json = "1.0"
serde_json_path = "0.6.0"
serde = "1.0"
sha2 = "0.10"
md-5 = "0.10"
hex = "0.4"
url = "2.4.0"
ordered-float = "3"

arrow = { workspace = true }
arrow-schema = {workspace = true, features = ["serde"]}
parquet = { workspace = true, features = ["async"]}
arrow-array = { workspace = true}
arrow-json = { workspace = true }

aws-sdk-kinesis = { version = "0.21", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-config = { version = "0.51", default-features = false, features = ["rt-tokio", "native-tls"] }
uuid = {version = "1.4.1", features = ["v4"]}
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"

tonic = { workspace = true }
prost = "0.12"

governor = "0.6"

#logging
tracing = "0.1"

# connectors
regex = "1.8.1"
anyhow = "1.0.71"
typify = "0.0.13"
regress = "0.6.0"
object_store = {workspace = true }
reqwest = "0.11.20"
memchr = "2.6.3"

datafusion = { workspace = true }
datafusion-proto = { workspace = true }
base64 = "0.21.5"
itertools = "0.12.0"
async-ffi = "0.5.0"
dlopen2 = "0.7.0"
dlopen2_derive = "0.4.0"


[dev-dependencies]
test-case = "3"
