[package]
name = "arroyo-worker"
version = "0.14.0-dev"
edition = "2021"

[features]
default = []

[dependencies]
arroyo-types = { path = "../arroyo-types" }
arroyo-state = { path = "../arroyo-state" }
arroyo-rpc = { path = "../arroyo-rpc" }
arroyo-server-common = { path = "../arroyo-server-common" }
arroyo-datastream = { path = "../arroyo-datastream" }
arroyo-planner = { path = "../arroyo-planner" }
arroyo-operator = { path = "../arroyo-operator" }
arroyo-connectors = { path = "../arroyo-connectors" }
arroyo-udf-host = { path = "../arroyo-udf/arroyo-udf-host" }

rand = "0.8"
bincode = "2.0.0-rc.3"
petgraph = "0.7"
prometheus = {version = "0.13", features = ["process"] }
futures = "0.3"
tokio = { version = "1", features = ["full", "tracing"] }
tokio-stream = { version = "0.1", features = ["full"] }
async-trait = "0.1.68"
async-stream = "0.3.4"
bytes = "1.4"
local-ip-address = "0.5"
serde_json = "1.0"
serde = "1.0"
ordered-float = "3"

arrow = { workspace = true }
arrow-schema = {workspace = true, features = ["serde"]}
arrow-array = { workspace = true}

tonic = { workspace = true }
prost = {workspace = true}

#logging
tracing = "0.1"

# connectors
anyhow = "1.0.71"

datafusion = { workspace = true }
datafusion-proto = { workspace = true }
itertools = "0.12.0"
mini-moka = { version = "0.10.3" }


[dev-dependencies]
test-case = "3"
