name: Setup Rust CI
description: Prepare the runner for Rust workspace CI jobs

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        components: clippy, rustfmt
        toolchain: 1.93

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: "3.12"

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.0.6
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Install runner dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang ruby unzip postgresql libsasl2-dev netcat-openbsd mosquitto

    - name: Install OpenAPI Generator
      shell: bash
      run: |
        pnpm install @openapitools/openapi-generator-cli -g
        cd crates/arroyo-openapi && openapi-generator-cli version

    - name: Build console
      shell: bash
      run: |
        cd webui
        pnpm build

    - name: Install CI tools
      shell: bash
      run: |
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C "${CARGO_HOME:-$HOME/.cargo}/bin"
        wget -q https://github.com/protocolbuffers/protobuf/releases/download/v21.8/protoc-21.8-linux-x86_64.zip -O /tmp/protoc.zip
        rm -rf /tmp/protoc
        unzip -q /tmp/protoc.zip bin/protoc -d /tmp/protoc
        sudo install /tmp/protoc/bin/protoc /usr/local/bin/protoc
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        wget -q https://github.com/rust-db/refinery/releases/download/0.8.7/refinery-0.8.7-x86_64-unknown-linux-musl.tar.gz -O /tmp/refinery.tgz
        rm -rf /tmp/refinery-unpack
        mkdir -p /tmp/refinery-unpack
        tar xzf /tmp/refinery.tgz -C /tmp/refinery-unpack
        install /tmp/refinery-unpack/refinery-*-musl/refinery /tmp/refinery
        rm -rf /tmp/kafka_2.13-3.9.2
        wget --progress=dot --show-progress https://dlcdn.apache.org/kafka/3.9.2/kafka_2.13-3.9.2.tgz -O /tmp/kafka.tgz
        tar xzf /tmp/kafka.tgz -C /tmp

    - name: Setup Postgres
      shell: bash
      run: |
        sudo systemctl start postgresql
        sudo -u postgres psql -c "CREATE USER arroyo WITH PASSWORD 'arroyo' SUPERUSER;"
        sudo -u postgres createdb arroyo
        /tmp/refinery migrate -e DATABASE_URL -p crates/arroyo-api/migrations

    - name: Setup Kafka
      shell: bash
      run: |
        mkdir -p /tmp/kraft-combined-logs
        /tmp/kafka_2.13-3.9.2/bin/kafka-storage.sh format -t 9v5PspiySuWU2l5NjTgRuA -c /tmp/kafka_2.13-3.9.2/config/kraft/server.properties
        /tmp/kafka_2.13-3.9.2/bin/kafka-server-start.sh -daemon /tmp/kafka_2.13-3.9.2/config/kraft/server.properties

    - name: Setup mosquitto
      shell: bash
      run: |
        sudo service mosquitto start
