name: Setup Rust CI
description: Prepare the runner for Rust workspace CI jobs

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        components: clippy, rustfmt
        toolchain: 1.93

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: "3.12"

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.0.6
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Install OpenAPI Generator
      shell: bash
      run: |
        pnpm install @openapitools/openapi-generator-cli -g
        cd crates/arroyo-openapi && openapi-generator-cli version

    - name: Build console
      shell: bash
      run: |
        cd webui
        pnpm build

    - name: Setup Postgres
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install postgresql
        sudo systemctl start postgresql
        sudo -u postgres psql -c "CREATE USER arroyo WITH PASSWORD 'arroyo' SUPERUSER;"
        sudo -u postgres createdb arroyo
        if ! cargo install --list | grep -q '^refinery_cli v0\.8\.14:'; then
          cargo install refinery_cli --version 0.8.14 --force
        fi
        ~/.cargo/bin/refinery migrate -e DATABASE_URL -p crates/arroyo-api/migrations

    - name: Install dependencies
      shell: bash
      run: |
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
        sudo apt-get install -y cmake clang ruby unzip postgresql protobuf-compiler libsasl2-dev netcat-openbsd
        if ! command -v wasm-pack >/dev/null 2>&1 || [ "$(wasm-pack --version)" != "wasm-pack 0.13.1" ]; then
          cargo install wasm-pack --locked --version 0.13.1 --force
        fi

    - name: Install Kafka
      shell: bash
      run: |
        wget --progress=dot --show-progress https://dlcdn.apache.org/kafka/3.9.2/kafka_2.13-3.9.2.tgz
        tar xvfz kafka*.tgz
        mkdir -p /tmp/kraft-combined-logs
        kafka_*/bin/kafka-storage.sh format -t 9v5PspiySuWU2l5NjTgRuA -c kafka_*/config/kraft/server.properties
        kafka_*/bin/kafka-server-start.sh -daemon kafka_*/config/kraft/server.properties

    - name: Install mosquitto
      shell: bash
      run: |
        sudo apt-get install -y mosquitto
        sudo service mosquitto start
